name: Ejercicio1

on: push
jobs:
  hola_mundo:
    runs-on: ubuntu-latest


    steps:
      - name: Descargar codigo
        run: pip install pytest
      - name: Bajar codigo
        uses: actions/checkout@v4
      - name: Probar codigo
        run: pytest test.py
