name: Workflow1

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Paso1
        run: pip install pytest
      - name: Bajar codigo
        uses: actions/checkout@v4
      - name: Probar codigo
        run: pytest main.py
